mod attach;
pub(super) mod background_refresh;
mod background_support;
mod checkout_main;
pub(super) mod children;
mod clear_chat;
pub(super) mod clone;
mod discord_channels;
pub(super) mod discovery;
mod discovery_capture;
mod dropr_overlay;
mod dropr_task_drill;
mod dropr_task_finish;
mod dropr_task_launch;
mod dropr_task_nav;
mod dropr_task_open;
mod dropr_task_settle;
pub(super) mod dropr_task_worker;
pub(super) mod dropr_tasks;
mod kill;
mod land;
mod lifecycle;
pub(super) mod merge;
pub(super) mod merge_queued;
mod merge_worker;
mod orphans;
pub(super) mod overseer_refresh;
mod pr;
mod pr_fallback;
pub(super) mod pr_precheck;
pub(super) mod preview_capture;
mod registry_sync;
mod rename;
mod settings;
pub(super) mod slots;
mod subagents;
