mod attach;
pub(super) mod background_refresh;
mod background_support;
mod children;
pub(super) mod clone;
pub(super) mod discovery;
pub(super) mod dropr_tasks;
mod kill;
mod lifecycle;
pub(super) mod merge;
mod orphans;
mod pr;
pub(super) mod preview_capture;
mod settings;
mod slots;
mod subagents;
